### PR TITLE
Add: isDeviceReady - detect no battery attached

### PR DESCRIPTION
**Pull request by tyeth**
Precursor to https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/pull/557

### CODE REVIEW

**Comment by tyeth** [comment]
@brentru if you wouldn't mind reviewing this first. 

Along with refactoring to use the new isDeviceReady function (and adding the defines), I've updated the examples to retry the begin statement every few seconds rather than an infinite loop, as it seemed more useful for demos.

**Comment by tyeth** [comment]
Tagging @ladyada for review, Brent doesn't have enough knowledge about this driver

**Comment by tyeth** [comment]
~ladyada Corrected as requested.~

**Comment by tyeth** [comment]
Should be okay now @ladyada - I retested it too.

**Review by ladyada — APPROVED** [review]

**Pull request merged**
